repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
  - repo: https://github.com/maltzj/google-style-precommit-hook
    sha: 95c2f5632710e095220e22cc1a4e1a1451abf75f
    hooks:
      - id: google-style-java
